worker_processes auto;

events { worker_connections 1024; }

http {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # PUBLIC LISTENER: only /public allowed
    server {
        listen 80;
        server_name public;

        location /public/user/ {
            proxy_pass http://user_api:3000/public/;
        }
        location /private/user/ {
            return 403;
        }

        location /public/supplier/ {
            proxy_pass http://supplier_api:3000/public/;
        }
        location /private/supplier/ {
            return 403;
        }

        location / {
            return 403;
        }
    }

    # PRIVATE LISTENER: allow both /public and /private for internal service comms/testing
    server {
        listen 8080;
        server_name private;

        location /public/user/ {
            proxy_pass http://user_api:3000/public/;
        }
        location /private/user/ {
            proxy_pass http://user_api:3000/private/;
        }

        location /public/supplier/ {
            proxy_pass http://supplier_api:3000/public/;
        }
        location /private/supplier/ {
            proxy_pass http://supplier_api:3000/private/;
        }

        location /rabbitmq/ {
            proxy_pass http://rabbitmq:15672;
            proxy_buffering off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}